model:
  model_params_b: 12
  hidden_size: 3840
  layers: 48
  kv_heads: 8
  head_dim: 240
  bytes_per_parameter: 2

training:
  show_training: True
  train_gpus: 4
  zero_stage: 3
  train_batch_size: 4
  train_overhead_percent: 50

inference:
  show_inference: True
  infer_gpus: 2
  infer_batch_size: 2
  infer_overhead_percent: 50

lora:
  use_lora: True
  rank: 256